-- Executed verbatim by alma.warehouse._create_schema. SQLite STRICT source DDL.
PRAGMA foreign_keys=ON;
CREATE TABLE products (id TEXT PRIMARY KEY,name TEXT NOT NULL,category TEXT NOT NULL,collection TEXT NOT NULL,lifecycle TEXT NOT NULL) STRICT;
CREATE TABLE variants (id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),size TEXT NOT NULL,color TEXT NOT NULL,price_cents INTEGER NOT NULL CHECK(price_cents>=0),cost_cents INTEGER) STRICT;
CREATE TABLE suppliers (id TEXT PRIMARY KEY,name TEXT NOT NULL) STRICT;
CREATE TABLE customers (id TEXT PRIMARY KEY,acquired_date TEXT NOT NULL CHECK(acquired_date LIKE '____-__-__')) STRICT;
CREATE TABLE campaigns (id TEXT PRIMARY KEY,name TEXT NOT NULL,channel TEXT NOT NULL,objective TEXT NOT NULL,start_date TEXT NOT NULL CHECK(start_date LIKE '____-__-__'),end_date TEXT NOT NULL CHECK(end_date LIKE '____-__-__')) STRICT;
CREATE TABLE purchase_orders (id TEXT PRIMARY KEY,supplier_id TEXT NOT NULL REFERENCES suppliers(id),variant_id TEXT NOT NULL REFERENCES variants(id),ordered_qty INTEGER NOT NULL CHECK(ordered_qty>=0),received_qty INTEGER NOT NULL CHECK(received_qty>=0),unit_cost_cents INTEGER NOT NULL CHECK(unit_cost_cents>=0),status TEXT NOT NULL,date TEXT NOT NULL CHECK(date LIKE '____-__-__'),paid_cents INTEGER NOT NULL CHECK(paid_cents>=0)) STRICT;
CREATE TABLE expenses (id TEXT PRIMARY KEY,date TEXT NOT NULL CHECK(date LIKE '____-__-__'),category TEXT NOT NULL,amount_cents INTEGER NOT NULL CHECK(amount_cents>=0),paid_cents INTEGER NOT NULL CHECK(paid_cents>=0),variable INTEGER NOT NULL CHECK(variable IN(0,1))) STRICT;
CREATE TABLE orders (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id),channel TEXT NOT NULL,campaign_id TEXT NOT NULL REFERENCES campaigns(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),delivered_date TEXT,status TEXT NOT NULL CHECK(status IN('delivered','shipped','paid','pending','cancelled'))) STRICT;
CREATE TABLE content_assets (id TEXT PRIMARY KEY,campaign_id TEXT NOT NULL REFERENCES campaigns(id),format TEXT NOT NULL,theme TEXT NOT NULL,published_date TEXT NOT NULL CHECK(published_date LIKE '____-__-__'),variant_id TEXT REFERENCES variants(id)) STRICT;
CREATE TABLE sessions (id TEXT PRIMARY KEY,customer_id TEXT REFERENCES customers(id),channel TEXT NOT NULL,campaign_id TEXT NOT NULL REFERENCES campaigns(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),content_asset_id TEXT REFERENCES content_assets(id)) STRICT;
CREATE TABLE order_items (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),variant_id TEXT NOT NULL REFERENCES variants(id),quantity INTEGER NOT NULL CHECK(quantity>=0),unit_price_cents INTEGER NOT NULL CHECK(unit_price_cents>=0),discount_cents INTEGER NOT NULL CHECK(discount_cents>=0),unit_cost_cents INTEGER) STRICT;
CREATE TABLE payments (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),amount_cents INTEGER NOT NULL CHECK(amount_cents>=0),status TEXT NOT NULL CHECK(status IN('settled','pending','failed'))) STRICT;
CREATE TABLE refunds (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),amount_cents INTEGER NOT NULL CHECK(amount_cents>=0),status TEXT NOT NULL CHECK(status IN('settled','pending'))) STRICT;
CREATE TABLE credit_notes (id TEXT PRIMARY KEY,order_item_id TEXT NOT NULL REFERENCES order_items(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),amount_cents INTEGER NOT NULL CHECK(amount_cents>=0),reason TEXT NOT NULL) STRICT;
CREATE TABLE returns (id TEXT PRIMARY KEY,order_item_id TEXT NOT NULL REFERENCES order_items(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),quantity INTEGER NOT NULL CHECK(quantity>=0),restock INTEGER NOT NULL CHECK(restock IN(0,1))) STRICT;
CREATE TABLE movements (id TEXT PRIMARY KEY,variant_id TEXT NOT NULL REFERENCES variants(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),kind TEXT NOT NULL CHECK(kind IN('opening','receipt','sale','return','adjustment','supplier_return')),quantity INTEGER NOT NULL,reference_id TEXT NOT NULL) STRICT;
CREATE TABLE reservations (id TEXT PRIMARY KEY,order_item_id TEXT NOT NULL REFERENCES order_items(id),quantity INTEGER NOT NULL CHECK(quantity>=0),status TEXT NOT NULL CHECK(status IN('active','released'))) STRICT;
CREATE TABLE funnel (id TEXT PRIMARY KEY,date TEXT NOT NULL CHECK(date LIKE '____-__-__'),channel TEXT NOT NULL,campaign_id TEXT NOT NULL REFERENCES campaigns(id),visits INTEGER,leads INTEGER,spend_cents INTEGER NOT NULL CHECK(spend_cents>=0)) STRICT;
CREATE TABLE unmet_demand (id TEXT PRIMARY KEY,date TEXT NOT NULL CHECK(date LIKE '____-__-__'),variant_id TEXT NOT NULL REFERENCES variants(id),quantity INTEGER NOT NULL CHECK(quantity>=0),reason TEXT NOT NULL) STRICT;
CREATE TABLE leads (id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES customers(id),session_id TEXT REFERENCES sessions(id),channel TEXT NOT NULL,campaign_id TEXT NOT NULL REFERENCES campaigns(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),intent TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN('open','converted','lost')),order_id TEXT REFERENCES orders(id),variant_id TEXT REFERENCES variants(id)) STRICT;
CREATE TABLE purchase_receipts (id TEXT PRIMARY KEY,purchase_order_id TEXT NOT NULL REFERENCES purchase_orders(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),quantity INTEGER NOT NULL CHECK(quantity>=0)) STRICT;
CREATE TABLE supplier_payments (id TEXT PRIMARY KEY,purchase_order_id TEXT NOT NULL REFERENCES purchase_orders(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),amount_cents INTEGER NOT NULL CHECK(amount_cents>=0)) STRICT;
CREATE TABLE shipments (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),status TEXT NOT NULL CHECK(status IN('in_transit','delivered')),delivered_date TEXT) STRICT;
CREATE TABLE invoices (id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES orders(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),amount_cents INTEGER NOT NULL CHECK(amount_cents>=0),status TEXT NOT NULL CHECK(status IN('issued','void')),kind TEXT NOT NULL CHECK(kind='management_statement')) STRICT;
CREATE TABLE expense_payments (id TEXT PRIMARY KEY,expense_id TEXT NOT NULL REFERENCES expenses(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),amount_cents INTEGER NOT NULL CHECK(amount_cents>=0)) STRICT;
CREATE TABLE inventory_counts (id TEXT PRIMARY KEY,variant_id TEXT NOT NULL REFERENCES variants(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),counted_qty INTEGER NOT NULL CHECK(counted_qty>=0)) STRICT;
CREATE TABLE experiments (id TEXT PRIMARY KEY,name TEXT NOT NULL,hypothesis TEXT NOT NULL,primary_metric TEXT NOT NULL,guardrail TEXT NOT NULL,start_date TEXT NOT NULL CHECK(start_date LIKE '____-__-__'),end_date TEXT NOT NULL CHECK(end_date LIKE '____-__-__'),status TEXT NOT NULL CHECK(status IN('completed','running'))) STRICT;
CREATE TABLE experiment_assignments (id TEXT PRIMARY KEY,experiment_id TEXT NOT NULL REFERENCES experiments(id),customer_id TEXT NOT NULL REFERENCES customers(id),arm TEXT NOT NULL CHECK(arm IN('control','treatment')),assigned_date TEXT NOT NULL CHECK(assigned_date LIKE '____-__-__'),UNIQUE(experiment_id,customer_id)) STRICT;
CREATE TABLE experiment_outcomes (id TEXT PRIMARY KEY,assignment_id TEXT NOT NULL REFERENCES experiment_assignments(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),converted INTEGER NOT NULL CHECK(converted IN(0,1)),net_revenue_cents INTEGER NOT NULL CHECK(net_revenue_cents>=0),contribution_cents INTEGER NOT NULL,returned INTEGER NOT NULL CHECK(returned IN(0,1)),UNIQUE(assignment_id)) STRICT;
CREATE TABLE lifecycle_events (id TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),date TEXT NOT NULL CHECK(date LIKE '____-__-__'),from_stage TEXT NOT NULL CHECK(from_stage IN('idea','sample','launched','clearance','retired')),to_stage TEXT NOT NULL CHECK(to_stage IN('idea','sample','launched','clearance','retired')),reason TEXT NOT NULL) STRICT;
CREATE TABLE coverage (table_name TEXT PRIMARY KEY,covered INTEGER NOT NULL CHECK(covered IN(0,1))) STRICT;
CREATE TABLE warehouse_manifest (key TEXT PRIMARY KEY,value TEXT NOT NULL) STRICT;
CREATE TABLE ingest_batches (content_hash TEXT PRIMARY KEY,ingested_at TEXT NOT NULL,row_count INTEGER NOT NULL CHECK(row_count>=0)) STRICT;
CREATE TABLE rejected_batches (content_hash TEXT PRIMARY KEY,rejected_at TEXT NOT NULL,error TEXT NOT NULL,payload_json TEXT NOT NULL) STRICT;
CREATE INDEX idx_orders_delivered_date ON orders(delivered_date);
CREATE INDEX idx_movements_variant_date ON movements(variant_id,date);
CREATE INDEX idx_payments_date ON payments(date);
CREATE INDEX idx_returns_date ON returns(date);
CREATE INDEX idx_leads_session_id ON leads(session_id);
CREATE INDEX idx_shipments_order_id ON shipments(order_id);
CREATE INDEX idx_variants_product_id ON variants(product_id);
CREATE INDEX idx_purchase_orders_supplier_id ON purchase_orders(supplier_id);
CREATE INDEX idx_purchase_orders_variant_id ON purchase_orders(variant_id);
CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_campaign_id ON orders(campaign_id);
CREATE INDEX idx_order_items_order_id ON order_items(order_id);
CREATE INDEX idx_order_items_variant_id ON order_items(variant_id);
CREATE INDEX idx_payments_order_id ON payments(order_id);
CREATE INDEX idx_returns_order_item_id ON returns(order_item_id);
CREATE INDEX idx_sessions_campaign_id ON sessions(campaign_id);
CREATE INDEX idx_purchase_receipts_po_id ON purchase_receipts(purchase_order_id);
CREATE INDEX idx_supplier_payments_po_id ON supplier_payments(purchase_order_id);
CREATE INDEX idx_experiment_assignments_experiment_id ON experiment_assignments(experiment_id);
